name: 🐛 Bug report
description: Report an issue with the Biome VS Code extension
title: "🐛 "
labels: ["Needs triage"]
body:
  - type: input
    attributes:
      label: "IDE and version"
      description: Name of the editor and its version
      placeholder: "WebStorm 1.86.1"
    validations:
      required: true
  - type: input
    attributes:
      label: "Extension version"
      description: Version of Biome JetBrains extension.
      placeholder: "2.0.0"
    validations:
      required: true
  - type: input
    attributes:
      label: "Biome version"
      description: The version of Biome that the extension is using.
      placeholder: "1.5.3"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Operating system"
      description: Check all operating systems on which you have observed the issue.
      options:
        - label: "Windows"
          required: false
        - label: "macOS"
          required: false
        - label: "Linux"
          required: false
  - type: textarea
    attributes:
      label: "Description"
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Does this issue occur when using the CLI directly?"
      options: ["Yes", "No", "Not sure / Not applicable"]
      default: 2
    validations:
      required: true
  - type: input
    attributes:
      label: "Link to a minimal reproduction"
      description: |
        A minimal reproduction of the issue. This should be a link to a git repository.

        Please be aware that **issues without a minimal reproduction are likely to be closed** without
        further investigation. We NEED to be able to reproduce the issue in order to understand it
        and fix it.

        Please use the `npm create @biomejs/biome-reproduction` command whenever you can to bootstrap a reproduction
        repository.
